### ISSUE TITLE
vk::Instance::enumeratePhysicalDevices: ErrorInitializationFailed

### ISSUE THREAD

**Issue by 1800012973** [haosulab/ManiSkill-Legacy#5]
Hello, an error occurred to me when I tried to make an maniskill environment, could you help me with it?

Traceback (most recent call last):
  File "1.py", line 4, in <module>
    env = gym.make('OpenCabinetDoor-v0')
  File "/scratch/makq/.conda/envs/mani_skill/lib/python3.8/site-packages/gym/envs/registration.py", line 145, in make
    return registry.make(id, **kwargs)
  File "/scratch/makq/.conda/envs/mani_skill/lib/python3.8/site-packages/gym/envs/registration.py", line 90, in make
    env = spec.make(**kwargs)
  File "/scratch/makq/.conda/envs/mani_skill/lib/python3.8/site-packages/gym/envs/registration.py", line 59, in make
    cls = load(self.entry_point)
  File "/scratch/makq/.conda/envs/mani_skill/lib/python3.8/site-packages/gym/envs/registration.py", line 18, in load
    mod = importlib.import_module(mod_name)
  File "/scratch/makq/.conda/envs/mani_skill/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/scratch/makq/ManiSkill/ManiSkill-SourceCode/mani_skill/env/open_cabinet_door_drawer.py", line 5, in <module>
    from mani_skill.env.base_env import BaseEnv
  File "/scratch/makq/ManiSkill/ManiSkill-SourceCode/mani_skill/env/base_env.py", line 59, in <module>
    _renderer = sapien.VulkanRenderer(default_mipmap_levels=1)
RuntimeError: vk::Instance::enumeratePhysicalDevices: ErrorInitializationFailed

**Comment by tongzhoumu** [comment]
Hi, this is probably because you did not install Nvidia driver or your Nvidia driver is broken. Please install Nvidia driver and `vulkan-utils`. You can check the installation of Nvidia driver by running `nvidia-smi`.

**Comment by fbxiang** [comment]
You need to ensure `/usr/share/vulkan/icd.d/nvidia_icd.json` exists, and just for safety you can set environment variable `VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json`. The package `vulkan-utils` will provide this file (but it is just a json file you can copy from other machines).

**Comment by 1800012973** [comment]
> You need to ensure `/usr/share/vulkan/icd.d/nvidia_icd.json` exists, and just for safety you can set environment variable `VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json`. The package `vulkan-utils` will provide this file (but it is just a json file you can copy from other machines).

Hi, I have installed vulkan-utils but there isn't `nvidia_icd.json` in it and the error still exists. Do you mind sending that json file to makq@pku.edu.cn? Thanks very much!

**Comment by 1800012973** [comment]
> > You need to ensure `/usr/share/vulkan/icd.d/nvidia_icd.json` exists, and just for safety you can set environment variable `VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json`. The package `vulkan-utils` will provide this file (but it is just a json file you can copy from other machines).
> 
> Hi, I have installed vulkan-utils but there isn't `nvidia_icd.json` in it and the error still exists. Do you mind sending that json file to [makq@pku.edu.cn](mailto:makq@pku.edu.cn)? Thanks very much!


It has been solved now, don't bother, thanks!

**Comment by SieRaX** [comment]
I am having the same issue. Nvidia driver is installed regularly `nvidia-smi` works. However, I couldn't find nvidia_icd.json file.  How did you solve this error?

**Comment by 2019EPWL** [comment]
> > > You need to ensure `/usr/share/vulkan/icd.d/nvidia_icd.json` exists, and just for safety you can set environment variable `VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json`. The package `vulkan-utils` will provide this file (but it is just a json file you can copy from other machines).
> > 
> > 
> > Hi, I have installed vulkan-utils but there isn't `nvidia_icd.json` in it and the error still exists. Do you mind sending that json file to [makq@pku.edu.cn](mailto:makq@pku.edu.cn)? Thanks very much!
> 
> It has been solved now, don't bother, thanks!

hi, I have a same problem as you, can you share how you solve the problem "RuntimeError: vk::Instance::enumeratePhysicalDevices: ErrorInitializationFailed", thanks!

**Comment by DanielTakeshi** [comment]
Did anyone solve this error? @1800012973 did you resolve it by getting that `json` file?
EDIT: never mind, better to completely purge and then reinstall the NVIDIA drivers. Copying `.json` files doesn't work.

**Comment by 2019EPWL** [comment]
no， I just reinstalled in a docker, then it worked.
